[features]
seeds = false
[programs.localnet]
solana_voting_d_app = "AmjsJBNZueExSeFWZ1RwcAuBnD3p7coprE63DiJ88s8p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/chamroeunsereyboth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
